version: "3"
services:
  api:
    build: .
    # depend_on:
    #   - postgres
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app
    # command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

    # env_file:
    #     - ./.env
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=1234
      - DATABASE_NAME=fastapi
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=bc35ac62d48e2a9c1c878795fa769de86d745eb781f176c0bc2b1cac8b5234ec
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=300
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - postgres
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=fastapi
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
